config/routes.rb
Rails.application.routes.draw do
    resources :books do  # tells you to go inside books
    	collection do
    		get 'search'
    	end
    	resources :user_ratings, except: [:index, :show]
    end

    get '/books/:id/details' => 'books#details', as: :details
    get '/books/search' => 'books#search'

    root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many   :user_ratings
  validates  :title, :prologue, :genre, :author, presence: true

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/s
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  has_many :user_ratings, dependent: :destroy

end

app/models/user_rating.rb
class UserRating < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :prologue, :genre, :author)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:star_rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: book, local: true) do |form| %>
      <% if book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, id: :book_title, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :prologue %>
        <%= form.text_area :prologue, id: :book_prologue, class: 'form-control'%>
      </div>

      <div class="field">
        <%= form.label :genre %>
        <%= form.text_field :genre, id: :book_genre, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :author %>
        <%= form.text_field :author, id: :book_author, class: 'form-control' %>
      </div><br>

      <div class="actions">
        <%= form.submit "Submit", class: "btn btn-primary"%>
      </div>
    <% end %>
 </div>
</div>

app/views/books/details.html.erb
<head>
  <style>
      h1 {color: red; text-align: center;}
      table {border: none; background-color: lightgreen; margin-left: 100px;}
      th, td {
        padding: 35px;
        padding-top: 1px;
        padding-bottom: 1px;
      }
      .panel-body {background-color: lightgreen; margin-bottom: none; }
      .book-path { margin-left: 135px; }
  </style>
</head>

<div class="panel panel-default">
  <div class="panel-body">
    <% if @user_ratings.blank? %>
      <h3>No ratings just yet, would you like to add the first!</h3>
      <%= link_to "Rate this book", new_book_user_rating_path(@book), class: "btn btn-danger" %>
    <% else %>
    <h1><%= @book.title %></h1><br>
      <table>
        <tr>
          <th>User</th>
          <th>Rating</th>
          <th>Comment</th>
        </tr>
      <% @user_ratings.each do |user_rating| %>
        <tr>
          <td><p><%= user_rating.user.email %></p></td>
          <td><p><%= user_rating.score %></p></td>
          <td>
            <div class="star-rating" data-score= <%= user_rating.score %> ></div>
            <p><%= user_rating.comment %></p>
          </td>
        </tr>
      <% end %>
    </table>
    <div class="book-path">
      <%= link_to 'Back', book_path %><br>
      <%= link_to "Rate this book", new_book_user_rating_path(@book) %>
    </div>
  <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Prologue</th>
      <th>Genre</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.prologue %></td>
        <td><%= book.genre %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<div class="row">
  <% @search_books.each do |book| %>
    <div class="col-sm-6 col-md-3">
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <div class="star-rating" data-score= <%= @average_rating %> ></div>
        <em><%= "#{@user_ratings.length} user ratings" %></em> |
        <% if @book.user_id == current_user.id %>
          <%= link_to 'Edit', edit_book_path(@book) %> |
          <%= link_to 'Delete', book_path(@book), method: :delete,
                       data: {confirm: "Really delete this book?"} %> |
        <% end %>
        <%= link_to 'Back', books_path %>

        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @book.title %></td>
              </tr>
              <tr>
                <td><strong>Author:</strong></td>
                <td><%= @book.author %></td>
              </tr>
              <tr>
                <td><strong>Genre:</strong></td>
                <td><%= @book.genre %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a Review", new_book_user_rating_path(@book) %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="user_rating_title"><%= @book.title %></h1>
        <p><%= @book.prologue %></p>

        <% if @user_ratings.blank? %>
          <h3>There's no any review yet, would you like to add the first!</h3>
          <%= link_to "Write Review", new_book_user_rating_path(@book), class: "btn btn-danger" %>
        <% else %>
          <% @user_ratings.each do |user_rating| %>
            <div class="user_ratings">
              <div class="star-rating" data-score= <%= user_rating.score %> ></div>
              <p><%= user_rating.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse bg-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "REVIEW APP", root_path, class: "navbar-brand" %>
    </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>
          <%= form_tag search_books_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
            <p>
              <%= text_field_tag :search, params[:search], class: "form-control" %>
              <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
            </p>
          <% end %>
     </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RatingSystem</title>
    <%= csrf_meta_tags %>
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :star_rating %>
    <%= form.text_field :star_rating, id: :user_star_rating %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :user_comment, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'user_rating[score]'
  });
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Star rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.star_rating %></td>
        <td><%= user.comment %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Star rating:</strong>
  <%= @user.star_rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @user.comment %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>